### PR TITLE
Identify Discord tokens

### LINKED ISSUE #93: Identify discord tokens
Here is la regex :
```[N]([a-zA-Z0-9]{23})\.([a-zA-Z0-9]{6})\.([a-zA-Z0-9]{27})```

### PR DESCRIPTION
**Pull request by amadejpapez**
- added regex for Discord tokens (fixes #93)
- changed `plural_name` value for Placekey to `False`

### CODE REVIEW

**Review by bee-san — APPROVED** [review]

**Comment by apteryxxyz** [comment]
Doesn't match tokens that start with O. Discord bot tokens can start with an O when the ID starts with an eight or nine (start of a token being the bots ID in base64).

**Comment by amadejpapez** [comment]
> Doesn't match tokens that start with O. Discord bot tokens can start with an O when the ID starts with an eight or nine (start of a token being the bots ID in base64).

I have only found examples starting with `N` or `M`. Do you have a link to one that starts with `O` and are you aware of any other letters?

**Comment by apteryxxyz** [comment]
> > Doesn't match tokens that start with O. Discord bot tokens can start with an O when the ID starts with an eight or nine (start of a token being the bots ID in base64).
> 
> I have only found examples starting with `N` or `M`. Do you have a link to one that starts with `O` and are you aware of any other letters?

The token of a bot I made recently: ODYyOTUyOTE3NTg4NjM5NzY1.YOf1iA.7lARgFXmodxpgmPvOXapaKUga6M (regenerated)
New Discord snowflake IDs have started starting with 8.
ODYyOTUyOTE3NTg4NjM5NzY1 is the bots ID in base64, so 862952917588639765.
I'm don't know of any other letters.

**Comment by amadejpapez** [comment]
Thank you very much for noticing this! I will add `O` to the regex and test it with the token you provided. :)

**Pull request merged**
