### PR TITLE
refactor tests/test_regex_identifier.py

### PR DESCRIPTION
**Pull request by jyooru**
**⚠ Pull Requests not made with this template will be automatically closed 🔥**

# Prerequisites
- [x] Have you read the documentation on contributing? https://github.com/bee-san/pyWhat/wiki/Adding-your-own-Regex

# Why do we need this pull request?

Currently, the tests files are quite long. I've attempted moving the test data into `regex.json` and using `pytest.mark.parmaterize` to "generate" tests using the test data now in `regex.json`. This makes it much easier to maintain `test_regex_identifier.py` as to change all `_assert_match_first_item` tests, you only have to change one test:

```py
@pytest.mark.parametrize(
    "name,match",
    [
        (regex["Name"], match)
        for regex in database
        for match in regex.get("Matches", [])
    ],
)
def test_regex_match(name: str, match: str):
    res = r.check([match])
    _assert_match_first_item(name, res)
```

# What [GitHub issues](https://github.com/bee-san/pyWhat/issues) does this fix?

Related to #199
Related to #195  

Contributions to this PR are welcome!

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Can you change "Matches" to "Examples"?

**Comment by jyooru** [comment]
> Can you change "Matches" to "Examples"?

Yeah, I'm planing on also adding some strings that should not be matched. Does something like this sound alright?
```json
{
  "Name": "Email Address",
  ...
  "Examples": {
    "Valid": ["firstname+lastname@example.com"],
    "Invalid": ["email@example@example.com"]
  }
}
```
```py
def test_email4():
    res = r.check(["email@example@example.com"])
    assert "Email Address" not in res
```

**Comment by piatrashkakanstantinass** [comment]
> > Can you change "Matches" to "Examples"?
> 
> 
> 
> Yeah, I'm planing on also adding some strings that should not be matched. Does something like this sound alright?
> 
> ```json
> 
> {
> 
>   "Name": "Email Address",
> 
>   ...
> 
>   "Examples": {
> 
>     "Valid": ["firstname+lastname@example.com"],
> 
>     "Invalid": ["email@example@example.com"]
> 
>   }
> 
> }
> 
> ```
> 
> ```py
> 
> def test_email4():
> 
>     res = r.check(["email@example@example.com"])
> 
>     assert "Email Address" not in res
> 
> ```

Amazing

**Comment by jyooru** [comment]
> This is great!! Makes it way easier for people to test their code, and it allows people in the future to see examples of things :D
> 
> happy to merge this, 1 question -- why is code coverage down? thinking other than that, it looks good to me :D !!! partying_face

Thanks!

Code coverage is down due to amount of lines of code removed, as pytest is practically just rerunning the function for each match. JSON does not contribute to coverage either. I will be checking that there is the same amount of test cases before and after, that way I know I haven't left anything out accidentally.

**Comment by jyooru** [comment]
Please squash!

**Review by bee-san — APPROVED** [review]

**Pull request merged**
