### PR TITLE
Easy integration module

### PR DESCRIPTION
**Pull request by roaldi**
I wanted to be able to import pywhat into a Splunk app I'm creating, and I figured more people than just myself would want an easy way to import its functionality into another script.

### CODE REVIEW

**Comment by roaldi** [comment]
It ain't much, but its honest work.

**Comment by bee-san** [comment]
Hey @roaldi , are you looking for the PyWhat API?

https://github.com/bee-san/pyWhat/wiki/API

**Comment by roaldi** [comment]
Yep, I'm just being silly, looking for problems that don't exist. Thanks.

**Comment by bee-san** [comment]
> Yep, I'm just being silly, looking for problems that don't exist. Thanks.

No worries! My fault for not including the docs in the README 😅

**Comment by roaldi** [comment]
Nah, can't believe I didn't see it in the code as I was poking and prodding.

**Comment by roaldi** [comment]
Actually, reopening this for 1 reason. Using this, I don't have to import rich or click, making it lighter weight. Thoughts?

**Comment by piatrashkakanstantinass** [comment]
Using API does not import rich or click.

**Comment by roaldi** [comment]
I stand corrected again, I had imported stuff weirdly. Going to use my way for the search command I'm making since I just need regex_identifier, but definitely already taken care of here. Sorry bout that!

**Comment by dawonp** [comment]
I want to hack an Instagram account that can help me

**Pull request closed without merging**
